### ISSUE TITLE
Write code for insertion sort in c language 

### ISSUE THREAD

**Issue by intrinsi** [intrinsi/dsa#25]

**Comment by Anonymous-Technopath** [comment]
Allow me to contribute to this

**Comment by Ash0069** [comment]
Hi @intrinsi, please assign this to me I have code ready for this

**Comment by Anirbansaha007** [comment]
Hi @intrinsi, I have solved the insertion sort program in C++ https://github.com/intrinsi/dsa/pull/28
Please check and merge my pull request.
